import { Cable, Users, Check, Minus } from 'lucide-react';
import type { Catalogue, Session, Command } from '../lib/domain.ts';

export function CrewPanel({ catalogue, session, busy, command }: { catalogue: Catalogue; session: Session; busy: boolean; command: (command: Command) => void }) {
  const available = catalogue.performers.filter(p => p.available && !session.unavailablePerformerIds.includes(p.id)).length;
  return <section className="crew-panel"><div className="panel-heading"><span className="eyebrow"><Users size={14}/> TONIGHT'S CREW</span><span className="small-count">{available}/{catalogue.performers.length}</span></div>
    <p className="panel-description">One change here can change the whole show.</p>
    <div className="crew-list">{catalogue.performers.map(person => { const here = person.available && !session.unavailablePerformerIds.includes(person.id); return <div className={`crew-row ${here ? '' : 'absent'}`} key={person.id}><span className="person-avatar">{person.initials}</span><div className="person-copy"><strong>{person.name}</strong><span>{person.role}</span></div><button role="switch" aria-checked={here} aria-label={`${person.name} availability`} className={`availability-switch ${here ? 'on' : ''}`} disabled={busy || !person.available} title={!person.available ? 'Marked unavailable in the source catalogue' : here ? 'Mark unavailable' : 'Mark available'} onClick={() => command({type:'performer',id:person.id,available:!here})}><span>{here ? <Check size={10}/> : <Minus size={10}/>}</span></button></div>; })}</div>
    <details className="gear-details"><summary><Cable size={14}/><span>Stage kit</span><span>{catalogue.instruments.filter(i => i.available && !session.unavailableInstrumentIds.includes(i.id)).length}/{catalogue.instruments.length} ready</span></summary><div className="gear-list">{catalogue.instruments.map(instrument => { const here = instrument.available && !session.unavailableInstrumentIds.includes(instrument.id); return <div className="gear-row" key={instrument.id}><span>{instrument.name}</span><button role="switch" aria-checked={here} aria-label={`${instrument.name} availability`} className={`availability-switch ${here ? 'on' : ''}`} disabled={busy || !instrument.available} title={!instrument.available ? 'Unavailable in the source catalogue' : 'Change availability'} onClick={() => command({type:'instrument',id:instrument.id,available:!here})}><span>{here ? <Check size={10}/> : <Minus size={10}/>}</span></button></div>; })}</div></details>
  </section>;
}
