import { Search, Plus, Check, CircleAlert, ArrowUpRight, GitBranch, Database, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import type { Catalogue, Session, Command } from '../lib/domain.ts';
import { assessSong, assessSet, formatDuration } from '../lib/engine.ts';

export function Repertoire({ catalogue, session, busy, command }: { catalogue: Catalogue; session: Session; busy: boolean; command: (command: Command) => void }) {
  const [query,setQuery] = useState('');
  const songs = catalogue.songs.filter(s => `${s.title} ${s.key} ${s.note}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="repertoire-view"><div className="view-intro"><span className="eyebrow">THE REPERTOIRE</span><h1>Twelve songs. More possibilities.</h1><p>Every arrangement knows who and what it needs.</p></div><label className="search-field"><Search size={17}/><input aria-label="Search repertoire" placeholder="Find a song, key, or arrangement…" value={query} onChange={event => setQuery(event.target.value)}/><span>{songs.length} songs</span></label><div className="repertoire-grid">{songs.map(song => {
    const assessment = assessSong(catalogue,session,song.id), included = session.songIds.includes(song.id);
    const timingIssues = assessSet(catalogue,{ ...session,songIds:[...session.songIds,song.id] }).issues;
    return <article className="repertoire-card" key={song.id}><div className="candidate-title"><h2>{song.title}</h2><span className="mono">{formatDuration(song.durationSeconds)}</span></div><div className="song-meta"><span>{song.key}</span><span>·</span><span>{song.bpm} BPM</span></div><p>{song.note}</p><div className="repertoire-people">{song.performerIds.map(id => catalogue.performers.find(p => p.id === id)?.name.split(' ')[0] ?? 'Missing performer').join(' / ')}</div><div className="repertoire-bottom"><span className={`status-pill ${included ? '' : assessment.ready ? 'good' : 'danger'}`}>{included ? <><Check size={12}/> In the set</> : assessment.ready ? 'Rehearsed' : 'Not ready'}</span><button className="icon-button" disabled={busy || included || !assessment.ready || timingIssues.length > 0} title={included ? 'Already in the set' : !assessment.ready ? assessment.issues.join(' ') : timingIssues.join(' ') || 'Add to the running order'} aria-label={`Add ${song.title} to set`} onClick={() => command({type:'add',songId:song.id})}><Plus size={17}/></button></div>{!assessment.ready && <p className="row-issue"><CircleAlert size={12}/>{assessment.issues.join(' ')}</p>}</article>;
  })}</div>{!songs.length && <div className="empty-state"><Search size={24}/><h3>No songs found.</h3><p>Try a title, musical key, or arrangement detail.</p></div>}</section>;
}

export function BuildNotes({ mode, projectId }: { mode: 'demo' | 'sanity'; projectId?: string }) {
  return <section className="notes-view"><div className="view-intro"><span className="eyebrow">BEHIND THE DESK</span><h1>The structure saves the show.</h1><p>A small content model with consequences you can see.</p></div><div className="notes-grid"><article><Database size={23}/><h2>Connected content</h2><p>A song references its performers and instruments. The show references its songs and venue. Those connections explain exactly why a change affects the running order.</p><div className="model-chain"><span>SHOW</span><i>→</i><span>SONGS</span><i>→</i><span>CREW + KIT</span></div></article><article><GitBranch size={23}/><h2>Review is a real state</h2><p>Draft → rehearsal → approved. Approval belongs to the exact set you reviewed. Changing the lineup or a material content requirement sends it back to draft.</p></article><article><ShieldCheck size={23}/><h2>The rules stay visible</h2><p>Replacements must be playable, rehearsed, and fit the venue's time limit. Ranking favors a similar energy and duration. The app recommends; a person approves.</p></article><article><h2>{mode === 'sanity' ? 'Connected to Sanity' : 'You are in the local demo'}</h2><p>{mode === 'sanity' ? 'The catalogue comes from Sanity Content Lake, and changes are saved to a separate session for this browser.' : 'This original fictional catalogue is bundled with the app. Each tab has its own demo. Changes survive reloads and clear when that tab closes. Live Sanity persistence starts when project access is configured.'}</p>{projectId && <p className="project-id">Project: {projectId}</p>}<a href="https://www.sanity.io/docs" target="_blank" rel="noreferrer">Explore Sanity <ArrowUpRight size={14}/></a></article></div><div className="notes-footnote"><span className="eyebrow">MADE FOR THE SANITY CHALLENGE · PATH TWO</span><p>Built with AI-assisted coding and deterministic readiness checks. Song titles, arrangements, and crew are original demonstration records. No audio or lyrics are included.</p></div></section>;
}
